version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  web:
    build: .
    restart: unless-stopped
    links:
      - "db:database"
    ports:
      - "8080:8080"
    depends_on:
      - db