version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped
  web:
    image: go-supervise
    restart: unless-stopped
    volumes:
        - ./server.config.yml:/server.config.yml
    links:
      - "db:database"
    ports:
      - "8080:11223"
    depends_on:
      - db
