version: '3'

services:
  db:
    image: mongo
    restart: unless-stopped

  server:
    image: docker.pkg.github.com/scottjr632/go-supervise/server:latest 
    restart: unless-stopped
    volumes:
        - ./server.config.yml:/server.config.yml
    links:
      - "db:database"
    ports:
      - "8080:11223"
    depends_on:
      - db

  # web:
  #   image: docker.pkg.github.com/scottjr632/go-supervise-client/client:latest 
  #   restart: unless-stopped
  #   links:
  #     - "server:server"
  #   ports:
  #     - "11221:80"
  #   depends_on:
  #     - server