server:
  port: 11223

services:
  checkupservice:
    interval: 35 
    uniqueids: true

datastore:
  dbname: go-service
  connectionstring: mongodb://database:27017

jwt:
  tokenname: access_token
  protectedpath: /api/protected