apiVersion: v1
kind: Pod
metadata:
  name: go-supervise-db 
  labels:
    app: go-supervise-db
spec:
  containers:
  - name: go-supervise-client-container
    image: mongo 
  imagePullSecrets:
  - name: githubregisterkey
---
apiVersion: v1
kind: Service
metadata:
  name: go-supervise-db
  labels:
    app: go-supervise-db
spec:
  ports:
  - protocol: TCP
    port: 27017 
    targetPort: 27017 

  selector:
    app: go-supervise-db 

