apiVersion: v1
kind: Pod
metadata:
  name: go-server 
  labels:
    app: go-supervise-server
spec:
  containers:
  - name: go-supervise-client-container
    image: docker.pkg.github.com/scottjr632/go-supervise/server:latest
    volumeMounts:
    - name: config-volume
      mountPath: /server.config.yml
      subPath: server.config.yml
  - name: mongodb
    image: mongo
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: config-volume
      configMap:
        name: go-supervise-server-config
  imagePullSecrets:
  - name: githubregisterkey
---
apiVersion: v1
kind: Service
metadata:
  name: go-supervise-server
  labels:
    app: go-supervise-server
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11223 

  selector:
    app: go-supervise-server 
