apiVersion: v1
kind: Pod
metadata:
  name: supervisor-client 
  labels:
    app: go-supervise-client
spec:
  containers:
  - name: go-supervise-client-container
    image: docker.pkg.github.com/scottjr632/go-supervise-client/client:latest 
    env:
    - name: SERVER_URI
      value: "http://${GO_SUPERVISE_SERVER_SERVICE_HOST}:${GO_SUPERVISE_SERVER_SERVICE_PORT}"
#      value: "http://localhost:80"
  imagePullSecrets:
  - name: githubregisterkey
---
apiVersion: v1
kind: Service
metadata:
  name: go-supervise-client
  labels:
    app: go-supervise-client
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31111 
    targetPort: 80

  selector:
    app: go-supervise-client 
